In [1]:
import pandas as pd
# Load the dataset
df = pd.read_csv('../data/raw/daily_aqi_by_county_2013.csv')  # Replace with your actual file path
df.head()

,State Name,county Name,State Code,County Code,Date,AQI,Category,Defining Parameter,Defining Site,Number of Sites Reporting
0,Alabama,Baldwin,1,3,2013-01-01,41,Good,PM2.5,01-003-0010,1
1,Alabama,Baldwin,1,3,2013-01-04,42,Good,PM2.5,01-003-0010,1
2,Alabama,Baldwin,1,3,2013-01-07,48,Good,PM2.5,01-003-0010,1
3,Alabama,Baldwin,1,3,2013-01-10,39,Good,PM2.5,01-003-0010,1
4,Alabama,Baldwin,1,3,2013-01-13,41,Good,PM2.5,01-003-0010,1

In [2]:
# Filter for California, San Diego only
df_san_diego = df[(df['State Name'] == 'California') & (df['county Name'] == 'San Diego')].copy()
df_date_aqi = df_san_diego[['Date', 'AQI']].copy()
df_date_aqi['Date'] = pd.to_datetime(df_date_aqi['Date'])

df_date_aqi.head()

            Date  AQI
25737 2013-01-01  160
25738 2013-01-02   73
25739 2013-01-03   75
25740 2013-01-04   82
25741 2013-01-05   93

In [3]:
df_date_aqi.to_csv("../data/processed/aqi_cleaned.csv", header=True, index=False)