In [6]:
import pandas as pd
import numpy as np

In [7]:
# Load the dataset. Note: Using semicolon as delimiter and specifying decimal comma
df = pd.read_csv('../data/raw/daily_precip_san_diego.csv', sep=',')
df.head()

       STATION STATION_NAME            DATE    HPCP
0  COOP:041424  CAMPO CA US  20130101 00:00  999.99
1  COOP:041424  CAMPO CA US  20130101 01:00  999.99
2  COOP:041424  CAMPO CA US  20130201 00:00  999.99
3  COOP:041424  CAMPO CA US  20130201 01:00  999.99
4  COOP:041424  CAMPO CA US  20130301 00:00  999.99

In [8]:
# Drop rows where station != sd
df = df[df["STATION_NAME"] == "SAN DIEGO INTERNATIONAL AIRPORT CA US"]
df = df[["HPCP", "DATE"]]
df.head()

    HPCP            DATE
48  0.00  20130101 01:00
49  0.00  20130106 07:00
50  0.00  20130106 08:00
51  0.00  20130106 14:00
52  0.01  20130106 17:00

In [9]:
df["DATE"] = pd.to_datetime(df["DATE"], format="%Y%m%d %H:%M").dt.strftime("%Y-%m-%d")
df["HPCP"] = df["HPCP"].apply(lambda x: 1 if x > 0 else 0)

df = df.reset_index(drop=True)

df.head()

   HPCP        DATE
0     0  2013-01-01
1     0  2013-01-06
2     0  2013-01-06
3     0  2013-01-06
4     1  2013-01-06

In [10]:
df.to_csv("../data/processed/precip_data_cleaned.csv",header=True )